### ISSUE TITLE
crush with emoji 

### ISSUE THREAD

**Issue by fiorins** [dawsonbooth/react-repo-card#19] opened 2021-11-10 16:26 UTC
hi, seems it crushes with emoji into the repo's description, because before I put it in it worked fine

**Comment by dawsonbooth** [comment] 2022-02-23 04:32
Hmm, unable to reproduce this:

![image](https://user-images.githubusercontent.com/10625031/155261400-8875ebf3-95d9-488a-955c-b9492dfc72d0.png)

Make sure you are using the latest version of the package, [v1.2.0](https://www.npmjs.com/package/react-repo-card).

Closing this for now, feel free to let me know if it persists and I'll re-open.

**Closed as completed by dawsonbooth** 2022-02-23 04:32 UTC
